# Generated by Django 4.1.3 on 2023-05-29 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TourPoint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=180)),
                ('Type', models.CharField(choices=[('Mo', 'Monastery'), ('Ma', 'Market'), ('Mn', 'Monument'), ('Wf', 'Water Fall'), ('Mt', 'Mountain'), ('Bg', 'Botanical Garden'), ('Zg', 'Zoological Garden'), ('Te', 'Tea Estate')], max_length=2)),
                ('Image', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('PhoneNumber', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=180)),
                ('Price', models.IntegerField()),
                ('Type', models.CharField(choices=[('PD', 'Pickup Drop'), ('TP', 'Tour Package')], max_length=2)),
                ('Description', models.CharField(max_length=200)),
                ('Image', models.URLField(max_length=500)),
                ('Itinerary', models.ManyToManyField(to='app.tourpoint', verbose_name='list of TourPoints')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Vehicle', models.CharField(choices=[('De', 'Desire - 4 seater'), ('Al', 'Alto - 4 seater'), ('Wg', 'WagonR - 5 seater'), ('In', 'Innova - 6 seater')], max_length=2)),
                ('DateBooked', models.DateField()),
                ('PrefDate', models.DateField()),
                ('SpecReq', models.TextField(max_length=500)),
                ('Package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.package')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
